#
# The MongoDB headless service. In brief, a headless service is one that doesn't
# prescribe load balancing. When combined with StatefulSets, this will give us
# individual DNSs to access our pods, and in turn a way to connect to all of our
# MongoDB nodes individually. In the yaml file, you can make sure that the
# service is headless by verifying that the clusterIP field is set to None.
#

apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  ports:
    - name: mongodb
      port: 27017
  clusterIP: None
  selector:
    app.kubernetes.io/name: mongodb