apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemisSecurity
metadata:
  name: passport-status-amq-security
spec:
  applyToCrNames:
    - passport-status-amq-staging
  loginModules:
    propertiesLoginModules:
    - name: prop-module-passport-status-amq-security-staging
      users:
      - name: passport-status-staging
        roles:
        - passport-status-user
  securityDomains:
    brokerDomain:
      name: activemq
      loginModules:
      - name: prop-module-passport-status-amq-security-staging
        flag: sufficient
  securitySettings:
    broker:
      - match: passport-statuses.#
        permissions:
          - operationType: consume
            roles:
              - passport-status-user
          - operationType: createDurableQueue
            roles:
              - passport-status-user
          - operationType: send
            roles:
              - passport-status-user
