apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: passport-status-db-cn-crunchy-import 
  labels:
    app.kubernetes.io/name: passport-status-db-cn-crunchy-import
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend 
    kind: SecretStore
  data:
    - secretKey: pg-user-password 
      remoteRef:
        key: PassportStatusAPI/env/staging
        property: postgres-user-password

---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: passport-status-db-cn
  labels:
    app.kubernetes.io/name: passport-status-db-cn
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend 
    kind: SecretStore
  data:
    - secretKey: username 
      remoteRef:
        key: PassportStatusAPI/env/staging
        property: postgresql-username
    - secretKey: password 
      remoteRef:
        key: PassportStatusAPI/env/staging
        property: postgresql-password
