apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mongodb
  serviceName: mongodb
  template:
    spec:
      containers:
        - name: mongodb
          imagePullPolicy: IfNotPresent
        - name: mongodb-sidecar
          imagePullPolicy: IfNotPresent
          env:
            - name: KUBERNETES_MONGO_SERVICE_NAME
              value: mongodb-staging
            - name: MONGO_SIDECAR_POD_LABELS
              value: "app.kubernetes.io/name=mongodb,app.kubernetes.io/instance=staging"
