apiVersion: apps/v1
kind: Deployment
metadata:
  name: passport-status-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: passport-status-api
      app.kubernetes.io/component: api
  template:
    spec:
      containers:
        - name: passport-status-api
          env:
            - name: SPRING_ARTEMIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: security-properties-prop-module-passport-status-amq-security-staging
                  key: passport-status-staging
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: passport-status-db-cn-staging
                  key: password
          livenessProbe:
            initialDelaySeconds: 120 
          readinessProbe:
            initialDelaySeconds: 120 
          # increase resources to accommodate database seeding
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1024Mi
