apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: passport-status-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: passport-status-api
  minReplicas: 1
  maxReplicas: 2 
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90 
  behavior:
    scaleUp:
      stabilizationWindow: 300
