apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: passport-status-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: passport-status-frontend
  minReplicas: 10
  maxReplicas: 30
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75