apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  # commonLabels must have at least one unique label
  # per environment to ensure selectors are applied correctly
  app.kubernetes.io/instance: nightly
bases:
  - ../../base/passport-status-api/
  - ../../base/passport-status-frontend/
images:
  - name: dtsrhpdevscedacr.azurecr.io/passport-status-api
    newTag: nightly
  - name: dtsrhpdevscedacr.azurecr.io/passport-status
    newTag: nightly
namespace: passport-status
nameSuffix: -nightly
patchesStrategicMerge:
  - passport-status-api-configmaps.yaml
  - passport-status-api-deployments.yaml
  - passport-status-frontend-configmaps.yaml
  - passport-status-frontend-deployments.yaml
resources:
  - artemis-deployments.yaml
  - artemis-security-deployments.yaml
  - passport-status-api-ingresses.yaml
  - passport-status-frontend-ingresses.yaml