apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  # commonLabels must have at least one unique label
  # per environment to ensure selectors are applied correctly
  app.kubernetes.io/instance: nightly
bases:
  - ../../base/passport-status-api/
namespace: passport-status
nameSuffix: -nightly
patchesStrategicMerge:
  - passport-status-api-configmaps.yaml
  - passport-status-api-deployments.yaml
resources:
  - artemis-deployments.yaml
  - artemis-security-deployments.yaml
  - passport-status-api-ingresses.yaml