apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/part-of: passport-status
  app.kubernetes.io/managed-by: kustomize
resources:
  - passport-status-api-cms.yaml
  - passport-status-api-deployments.yaml
  - passport-status-api-services.yaml