apiVersion: apps/v1
kind: Deployment
metadata:
  name: passport-status-frontend
  labels:
    app.kubernetes.io/name: passport-status-frontend
    app.kubernetes.io/component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: passport-status-frontend
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: passport-status-frontend
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: passport-status-frontend
          image: dtsrhpdevscedacr.azurecr.io/passport-status:latest
          ports:
            - name: http
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 250m
              memory: 512Mi
          volumeMounts:
            - name: config
              mountPath: /app/.env
              subPath: .env
      volumes:
        - name: config
          configMap:
            name: passport-status-frontend-cm
  strategy:
    rollingUpdate:
      maxUnavailable: 0%
      maxSurge: 100%
