apiVersion: v1
kind: Service
metadata:
  name: passport-status-frontend
spec:
  ports:
    - name: http
      port: 3000
  selector:
    app.kubernetes.io/name: passport-status-frontend
    app.kubernetes.io/component: frontend