apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: passport-status-amq
spec:
  deploymentPlan:
    size: 3
    image: placeholder
    messageMigration: true
    persistenceEnabled: true
    requireLogin: true
    # Issue: Artemis in kubernetes cluster doesn't start with persistance enabled equal to true
    # https://github.com/artemiscloud/activemq-artemis-operator/issues/187
    podSecurityContext:
      fsGroup: 0
      fsGroupChangePolicy: "OnRootMismatch"
  console:
    expose: true

---
#Temporary until we figure out how to auto provision the ingress with the ActiveMQArtemis spec.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: passport-status-amq-wconsj
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  ingressClassName: nginx
  rules:
    - host: passport-status-amq-wconsj-0.prod-dp-internal.dts-stn.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: passport-status-amq-prod-wconsj-0-svc
                port:
                  name: wconsj-0
    - host: passport-status-amq-wconsj-1.prod-dp-internal.dts-stn.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: passport-status-amq-prod-wconsj-1-svc
                port:
                  name: wconsj-1
    - host: passport-status-amq-wconsj-2.prod-dp-internal.dts-stn.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: passport-status-amq-prod-wconsj-2-svc
                port:
                  name: wconsj-2
