apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: passport-status-db-cn
  labels:
    app.kubernetes.io/name: passport-status-db-cn
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend 
    kind: SecretStore
  data:
    - secretKey: username 
      remoteRef:
        key: PassportStatusAPI/env/prod
        property: postgresql-username
    - secretKey: password 
      remoteRef:
        key: PassportStatusAPI/env/prod
        property: postgresql-password
