apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  # commonLabels must have at least one unique label
  # per environment to ensure selectors are applied correctly
  app.kubernetes.io/instance: prod
bases:
  - ../../base/passport-status-api/
  - ../../base/passport-status-db-cn/
  - ../../base/passport-status-frontend/
  - ../../base/passport-status-maintenance/
images:
  - name: dtsrhpdevscedacr.azurecr.io/passport-status
    newName: dtsrhpprodscedspokeacr.azurecr.io/passport-status
    newTag: 20241210-00362-0d989f18
  - name: dtsrhpdevscedacr.azurecr.io/passport-status-api
    newName: dtsrhpprodscedspokeacr.azurecr.io/passport-status-api
    newTag: 20241210-00101-636a993b
  - name: dtsrhpdevscedacr.azurecr.io/passport-status-maintenance
    newName: dtsrhpprodscedspokeacr.azurecr.io/passport-status-maintenance
    newTag: 20230127-00011-e434d1d5
namespace: passport-status
nameSuffix: -prod
patchesStrategicMerge:
  - ./passport-status-api-configmaps.yaml
  - ./passport-status-api-deployments.yaml
  - ./passport-status-frontend-configmaps.yaml
  - ./passport-status-frontend-deployments.yaml
  - ./passport-status-maintenance-deployments.yaml
resources:
  - ./artemis-deployments.yaml
  - ./artemis-security-deployments.yaml
  - ./external-secrets.yaml
  - ./passport-status-api-hpas.yaml
  - ./passport-status-api-ingresses.yaml
  - ./passport-status-frontend-hpas.yaml
  - ./passport-status-frontend-ingresses.yaml
  - ./two-year-retention-cronjob.yaml
secretGenerator:
  - name: passport-status-api
    envs:
      - ./.env.api.secret
patches:
  - target:
      kind: Cluster
      name: passport-status-db-cn
    patch: |-
      - op: replace
        path: /spec/instances
        value: 3
      - op: replace
        path: /spec/storage/size
        value: 1024Gi
      - op: replace
        path: /spec/bootstrap/initdb/secret/name
        value: passport-status-db-cn-prod
  - target:
      kind: Pooler
      name: passport-status-db-cn-pooler-rw
    patch: |-
      - op: replace
        path: /spec/cluster/name
        value: passport-status-db-cn-prod
