apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  # commonLabels must have at least one unique label
  # per environment to ensure selectors are applied correctly
  app.kubernetes.io/instance: prod
bases:
  - ../../base/passport-status-api/
  - ../../base/passport-status-frontend/
  - ../../base/passport-status-maintenance/
images:
  - name: dtsrhpdevscedacr.azurecr.io/passport-status
    newName: dtsprodcontainers.azurecr.io/passport-status
    newTag: TC-170-dev
  - name: dtsrhpdevscedacr.azurecr.io/passport-status-api
    newName: dtsprodcontainers.azurecr.io/passport-status-api
    newTag: 0.0.0-a24b5e5f
  - name: dtsrhpdevscedacr.azurecr.io/passport-status-maintenance
    newName: dtsprodcontainers.azurecr.io/passport-status-maintenance
    newTag: 20230106-12-e434d1d5
namespace: passport-status
nameSuffix: -prod
patchesStrategicMerge:
  - passport-status-api-configmaps.yaml
  - passport-status-api-deployments.yaml
  - passport-status-frontend-configmaps.yaml
  - passport-status-frontend-deployments.yaml
  - passport-status-maintenance-deployments.yaml
resources:
  - artemis-deployments.yaml
  - artemis-security-deployments.yaml
  - passport-status-api-hpas.yaml
  - passport-status-api-ingresses.yaml
  - passport-status-frontend-hpas.yaml
  - passport-status-frontend-ingresses.yaml