apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  # commonLabels must have at least one unique label
  # per environment to ensure selectors are applied correctly
  app.kubernetes.io/instance: prod
bases:
  - ../../base/passport-status-api/
  - ../../base/passport-status-db/
  - ../../base/passport-status-frontend/
  - ../../base/passport-status-maintenance/
images:
  - name: dtsrhpdevscedacr.azurecr.io/passport-status
    newName: dtsrhpprodscedspokeacr.azurecr.io/passport-status
    newTag: 20231208-00246-03071a6b
  - name: dtsrhpdevscedacr.azurecr.io/passport-status-api
    newName: dtsrhpprodscedspokeacr.azurecr.io/passport-statuspi
    newTag: 20231106-00061-2ae8071d
  - name: dtsrhpdevscedacr.azurecr.io/passport-status-maintenance
    newName: dtsrhpprodscedspokeacr.azurecr.io/passport-status-maintenance
    newTag: 20230127-00011-e434d1d5
namespace: passport-status
nameSuffix: -prod
patchesStrategicMerge:
  - ./passport-status-api-configmaps.yaml
  - ./passport-status-api-deployments.yaml
  - ./passport-status-frontend-configmaps.yaml
  - ./passport-status-frontend-deployments.yaml
  - ./passport-status-maintenance-deployments.yaml
resources:
  - ./artemis-deployments.yaml
  - ./artemis-security-deployments.yaml
  - ./passport-status-api-hpas.yaml
  - ./passport-status-api-ingresses.yaml
  - ./passport-status-frontend-hpas.yaml
  - ./passport-status-frontend-ingresses.yaml
secretGenerator:
  - name: passport-status-api
    envs:
      - ./.env.api.secret
patches:
  - target:
      kind: PostgresCluster
      name: passport-status-db
    patch: |-
      - op: replace
        path: /spec/instances/0/dataVolumeClaimSpec/resources/requests/storage
        value: 2048Gi
      - op: replace
        path: /spec/backups/pgbackrest/repos/0/volume/volumeClaimSpec/resources/requests/storage
        value: 2048Gi
      - op: replace
        path: /spec/backups/pgbackrest/global/repo1-retention-full-type
        value: time # Switch retention to be based on number of days. 
      - op: replace
        path: /spec/backups/pgbackrest/global/repo1-retention-full
        value: '1' # Patch to only store the last 14 days of backups.
      - op: replace
        path: /spec/instances/0/affinity/podAntiAffinity/preferredDuringSchedulingIgnoredDuringExecution/0/podAffinityTerm/labelSelector/matchLabels/postgres-operator.crunchydata.com~1cluster
        value: passport-status-db-prod
      - op: replace
        path: /spec/proxy/pgBouncer/affinity/podAntiAffinity/preferredDuringSchedulingIgnoredDuringExecution/0/podAffinityTerm/labelSelector/matchLabels/postgres-operator.crunchydata.com~1cluster
        value: passport-status-db-prod
      - op: replace
        path: /spec/databaseInitSQL/name
        value: passport-status-db-prod
