apiVersion: v1
kind: ConfigMap
metadata:
  name: passport-status-frontend-cm
data:
  .env: |-
    # Base URI for the Application
    NEXT_PUBLIC_APP_BASE_URI=https://etatpasseport-passportstatus.service.canada.ca
    # Base URI for the Passport Status API
    PASSPORT_STATUS_API_BASE_URI=http://passport-status-api-prod.passport-status.svc.cluster.local

    # Adobe Analytics Script Source
    NEXT_PUBLIC_ADOBE_ANALYTICS_SCRIPT_SRC=https://assets.adobedtm.com/be5dfd287373/9b9cb7867b5b/launch-59d77766b86a.min.js

    NEXT_PUBLIC_ENVIRONMENT=prod

    # Base URI for fetching Alerts from Principle Publisher
    ALERT_JSON_URI=https://www.canada.ca/content/dam/esdc-edsc/documents/services/notices/passportStatus.json
