apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: passport-status-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: passport-status-api
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 180 
