apiVersion: v1
kind: ConfigMap
metadata:
  name: passport-status-frontend-cm
data:
  .env: |-
    # Base URI for the Passport Status API
    PASSPORT_STATUS_API_BASE_URI=http://passport-status-api-prod.passport-status.svc.cluster.local:8080