apiVersion: v1
kind: ConfigMap
metadata:
  name: passport-status-api-cm
data:
  application.yaml: |-
    application:
      database-initializer:
        generated-statuses-number: 100_000
      security:
        content-security-policy:
          default-src: "'self'"
          connect-src: "'self' login.microsoftonline.com passport-status-api.prod-dp-internal.dts-stn.com"
          img-src: "'self' data:"
          script-src: "'self' 'sha256-4IiDsMH+GkJlxivIDNfi6qk0O5HPtzyvNwVT3Wt8TIw='"
        oauth:
          client-id: de3625ec-c6e6-46a6-b761-7b1039ab546a
          tenant-id: 9ed55846-8a81-4246-acd8-b1a01abfc0d1
      gcnotify:
        file-number-notification:
          english-template-id: 1d03e4f6-c119-4494-bf2b-cf41d3103819
          french-template-id: ee9ed87e-5cff-4894-aa7d-af12904c0944

    logging:
      level:
        '[ca.gov.dtsstn.passport.api]': info

    management:
      metrics:
        export:
          dynatrace:
            enabled: true
            uri: https://dynatrace.prod-dp.admin.dts-stn.com/e/676a0299-9802-4933-99d4-481318a557db/api/v2/metrics/ingest
            v2:
              default-dimensions:
                stack: prod
                region: canadacentral

    spring:
      artemis:
        broker-url: tcp://passport-status-amq-prod-hdls-svc:61616
        embedded:
          enabled: false
        mode: NATIVE
        user: passport-status-prod
      datasource:
        url: jdbc:postgresql://prod-postgresql-ha-pgpool/passport-status
        username: passport-status