apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: postgres-operator
  app.kubernetes.io/part-of: passport-status
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/version: 5.3.1 # The version below should match the version on the PostgresCluster CRD
resources:
  - manager.yaml
  - manager-upgrade.yaml
  - role_binding.yaml
  - role_binding-upgrade.yaml
  - role.yaml
  - role-upgrade.yaml
  - service_account.yaml
  - service_account-upgrade.yaml
images:
  - name: postgres-operator
    newName: registry.developers.crunchydata.com/crunchydata/postgres-operator
    newTag: ubi8-5.3.1-0
  - name: postgres-operator-upgrade
    newName: registry.developers.crunchydata.com/crunchydata/postgres-operator-upgrade
    newTag: ubi8-5.3.1-0
