apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/part-of: passport-status
  app.kubernetes.io/managed-by: kustomize
resources:
  - service_account.yaml
  - role.yaml
  - role_binding.yaml
  - election_role.yaml
  - election_role_binding.yaml
  - operator_config.yaml
  - operator.yaml