apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemisSecurity
metadata:
  name: passport-status-amq-security
spec:
  applyToCrNames:
    - passport-status-amq-dev
  loginModules:
    propertiesLoginModules:
    - name: prop-module-passport-status-amq-security-dev
      users:
      - name: passport-status-dev
        roles:
        - passport-status-user
  securityDomains:
    brokerDomain:
      name: activemq
      loginModules:
      - name: prop-module-passport-status-amq-security-dev
        flag: sufficient
  securitySettings:
    broker:
      - match: passport-status-address.passport-statuses
        permissions:
          - operationType: consume
            roles:
              - passport-status-user
          - operationType: send
            roles:
              - passport-status-user
