apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  # commonLabels must have at least one unique label
  # per environment to ensure selectors are applied correctly
  app.kubernetes.io/instance: dev
bases:
  - ../../base/passport-status-api/
  - ../../base/passport-status-maintenance/
namespace: passport-status
nameSuffix: -dev
patchesStrategicMerge:
  - passport-status-api-configmaps.yaml
  - passport-status-api-deployments.yaml
  - passport-status-maintenance-deployments.yaml
resources:
  - artemis-deployments.yaml
  - artemis-security-deployments.yaml
  - passport-status-api-ingresses.yaml
secretGenerator:
- name: passport-status-api
  envs:
  - .env.api.secret