apiVersion: v1
kind: ConfigMap
metadata:
  name: passport-status-frontend-cm
data:
  .env: |-
    # Base URI for the Application
    APP_BASE_URI=https://passport-status-dev.dev-dp-internal.dts-stn.com

    # Provide environment to front end application to determine whether or not to show test site banner
    ENVIRONMENT=dev

    # Base URI for the Passport Status API
    PASSPORT_STATUS_API_BASE_URI=http://passport-status-api-dev.passport-status.svc.cluster.local
