apiVersion: apps/v1
kind: Deployment
metadata:
  name: passport-status-api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: passport-status-api
      app.kubernetes.io/component: api
  template:
    spec:
      containers:
        - name: passport-status-api
          envFrom:
            - secretRef:
                name: passport-status-api-dev
          # increase resources because of embedded h2
          resources:
            requests:
              cpu: 2000m
              memory: 512Mi
            limits:
              cpu: 4000m
              memory: 2048Mi